---
dist: bionic
addons:
  apt:
    packages:
      - graphviz

language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2
  - node_modules

before_install:
  - curl -sL https://deb.nodesource.com/setup_11.x | sudo bash -
  - sudo apt install nodejs
  - npm install decktape

script:
  - node node_modules/decktape/decktape.js -s 3200x1800 --slides 1-500 reveal "file:///${TRAVIS_BUILD_DIR}/target/generated-slides/index.html?fragments=true" target/generated-slides/slides.pdf  

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: output
  on:
    branch: master
